#!/bin/bash

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    popd > /dev/null
    exit
}

if [[ -z "${POSHC2_DIR}" ]]; then
     POSH_DIR="/opt/PoshC2"
else
     POSH_DIR=${POSHC2_DIR}
fi

POSH_PROJECT_DIR=`cat $POSH_DIR/config.yml | grep "PoshProjectDirectory: " | cut -d "\"" -f 2`
DATABASE_TYPE=`cat $POSH_DIR/config.yml | grep "DatabaseType: " | cut -d "\"" -f 2`
DATABASE_STRING=`cat $POSH_DIR/config.yml | grep "PostgresConnectionString: " | cut -d "\"" -f 2`

pushd "$POSH_DIR" >/dev/null

if [ "$?" -eq "0" ]; then

    python3 -m pipenv run python3 "resources/scripts/fpc.py" -p "$POSH_PROJECT_DIR" -d "$DATABASE_TYPE" -pg "$DATABASE_STRING" $@
    popd > /dev/null

fi 

