#!/bin/bash

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    popd >/dev/null
    exit
}

source /usr/bin/_posh-common
get_posh_projects_dir

if [ "$1" == "-n" ]; then

    if [ -z "$2" ]; then
        echo "[*] Usage: posh-project -n <new-project-name>"
        exit 1
    fi

    if [ -d "$POSH_PROJECTS_DIR/$2" ]; then
        echo "[-] Project directory already exists: $POSH_PROJECTS_DIR/$2"
        exit 1
    fi

    sudo mkdir -p "$POSH_PROJECTS_DIR/$2"
    echo "$2" | sudo tee "$POSH_PROJECTS_DIR/CURRENT_PROJECT" >/dev/null
    sudo cp "$POSH_PROJECTS_DIR/config-template.yml" "$POSH_PROJECTS_DIR/$2/config.yml"
    echo "[+] Created Project: $2"

elif [ "$1" == "-s" ]; then
    if [ -z "$2"]; then
        echo "[*] Usage: posh-project -s <project-to-switch-to>"
        exit 1
    fi

    if [ ! -d "$POSH_PROJECTS_DIR/$2" ]; then
        echo "[-] Project directory does not exist: $POSH_PROJECTS_DIR/$2"
        exit 1
    fi
    echo "$2" | sudo tee $POSH_PROJECTS_DIR/CURRENT_PROJECT >/dev/null
    echo "[+] Switched to: $2"
    echo "[*] Restart the PoshC2 C2 server & ImplantHandler to use the new project."
else
    echo "[*] Usage: posh-project -n <new-project-name>"
    echo "[*] Usage: posh-project -s <project-to-switch-to>"
fi