#!/bin/bash

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    popd > /dev/null
    exit
}
    
if [[ -z "${POSHC2_DIR}" ]]; then
    POSH_DIR="/opt/PoshC2"
else
    POSH_DIR=${POSHC2_DIR} 
fi

POSH_PROJECT_DIR=`cat $POSH_DIR/config.yml | grep "PoshProjectDirectory: " | cut -d "\"" -f 2`

pushd $POSH_DIR  >/dev/null

if [ "$?" -eq "0" ]; then

    sudo systemctl enable poshc2.service >/dev/null
    sudo systemctl restart poshc2.service >/dev/null
	while [[ $x -le 10 ]]; do
	  if [ -f "$POSH_PROJECT_DIR/poshc2_server.log" ]; then
		  break;
	  fi
    sleep 1s
    x=$(( $x + 1 ))
  done
    /usr/bin/posh-log
    popd > /dev/null

fi 

