#!/bin/bash

if [[ -z "${POSHC2_DIR}" ]]; then
     POSH_DIR="/opt/PoshC2"
else
     POSH_DIR=${POSHC2_DIR}
fi

if [[ "$EDITOR" != "" ]]; then
    sudo $EDITOR "$POSH_DIR/config.yml"
elif [[ "$*" == *"--nano"* ]]; then
    sudo nano "$POSH_DIR/config.yml"
else
    sudo vim "$POSH_DIR/config.yml"
fi
