#!/bin/bash

POSH_PROJECT=`cat $HOME/.poshc2/CURRENT_PROJECT 2>/dev/null`
if [ -z "$POSH_PROJECT" ]; then
    echo "No PoshC2 project set, please run posh-project"
    exit 1
fi

POSH_PROJECT_DIR="$HOME/.poshc2/$POSH_PROJECT"
if [ ! -d "$POSH_PROJECT_DIR" ]; then
    echo "No PoshC2 project directory, please run posh-project"
    exit 1
fi

tail -n 5000 -f "$POSH_PROJECT_DIR/poshc2_server.log" 2>/dev/null\
	|| ( echo -e "\e[31m[!] Could not open logfile: "$POSH_PROJECT_DIR/poshc2_server.log"\e[0m")

