#!/bin/bash

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    popd > /dev/null
    exit
}

source /usr/local/bin/_posh-common
get_posh_dir
get_posh_project_dir

pushd $POSH_DIR  >/dev/null
if [ "$?" -eq "0" ]; then

    sudo python3 -m pipenv run python3 -u start.py --server 2>&1 | tee -a "$POSH_PROJECT_DIR/poshc2_server.log"
    popd > /dev/null
fi

