#!/bin/bash

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    popd > /dev/null
    exit
}

SCRIPT_LOCATION=`readlink -f -n $0`
POSH_DIR="`dirname $SCRIPT_LOCATION`/../../"

POSH_PROJECT=`cat $HOME/.poshc2/CURRENT_PROJECT 2>/dev/null`
if [ -z "$POSH_PROJECT" ]; then
    echo "No PoshC2 project set, please run posh-project"
    exit 1
fi

POSH_PROJECT_DIR="$HOME/.poshc2/$POSH_PROJECT"
if [ ! -d "$POSH_PROJECT_DIR" ]; then
    echo "No PoshC2 project directory, please run posh-project"
    exit 1
fi

pushd $POSH_DIR  >/dev/null
if [ "$?" -eq "0" ]; then

    sudo python3 -m pipenv run python3 -u start.py --server 2>&1 | tee -a "$POSH_PROJECT_DIR/poshc2_server.log"
    popd > /dev/null
fi

