#!/bin/bash

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    popd > /dev/null
    exit
}

SCRIPT_LOCATION=`readlink -f -n $0`
POSH_DIR="`dirname $SCRIPT_LOCATION`/../../"

pushd $POSH_DIR  >/dev/null

if [ "$?" -eq "0" ]; then

    echo ""
    echo -e """\033[92m
       __________            .__.     _________  ________
       \_______  \____  _____|  |__   \_   ___ \ \_____  \\
        |     ___/  _ \/  ___/  |  \  /    \  \/  /  ____/
        |    |  (  <_> )___ \|   Y  \ \     \____/       \\
        |____|   \____/____  >___|  /  \______  /\_______ \\
                           \/     \/          \/         \/
        ================= www.PoshC2.co.uk ================"""
    echo ""
    echo "[+] Updating PoshC2"
    echo ""

    if [[ $(id -u) -ne 0 ]]; then
        echo -e "You must run this installer as root.\nQuitting!";
        exit 1;
    fi

    echo ""
    echo "[+] Updating Posh Installation to latest master"
    git fetch
    git reset --hard origin/master

    echo ""
    echo "[+] Running Install script"
    ./Install.sh

    echo ""
    echo "[+] Update complete"
    echo ""

    popd > /dev/null
fi
