#!/bin/bash

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    popd >/dev/null
    exit
}

SCRIPT_LOCATION=`readlink -f -n $0`
POSH_DIR="`dirname $SCRIPT_LOCATION`/../../"

pushd "$POSH_DIR" >/dev/null

if [ "$?" -eq "0" ]; then
    sudo python3 -m pipenv run python3 start.py --client "$@"
    popd > /dev/null
fi
