#!/bin/bash

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    popd > /dev/null
    exit
}

SCRIPT_LOCATION=`readlink -f -n $0`
POSH_DIR="`dirname $SCRIPT_LOCATION`/../../"

pushd "$POSH_DIR"  >/dev/null

if [ "$?" -eq "0" ]; then
    posh-docker-clean
    sudo -E docker build -t m0rv4i/poshc2 . "$@"
    popd > /dev/null
fi

