#!/bin/bash

POSH_PROJECT=`cat $HOME/.poshc2/CURRENT_PROJECT 2>/dev/null`
if [ -z "$POSH_PROJECT" ]; then
    echo "No PoshC2 project set, please run posh-project"
    exit 1
fi

POSH_PROJECT_DIR="$HOME/.poshc2/$POSH_PROJECT"
if [ ! -d "$POSH_PROJECT_DIR" ]; then
    echo "No PoshC2 project directory, please run posh-project"
    exit 1
fi

sudo systemctl enable poshc2-docker.service >/dev/null
sudo systemctl restart poshc2-docker.service >/dev/null

while [[ $x -le 10 ]]; do
    if [ -f "$POSH_PROJECT_DIR/poshc2_server.log" ]; then
        break;
    fi
    sleep 1s
    x=$(( $x + 1 ))
done

/usr/bin/posh-log