#!/bin/bash

if [[ -z "${POSHC2_DIR}" ]]; then
    POSH_DIR="/opt/PoshC2"
else
    POSH_DIR="${POSHC2_DIR}"
fi

POSH_PROJECT_DIR=`cat $POSH_DIR/config.yml | grep "PoshProjectDirectory: " | cut -d "\"" -f 2`


read -p "Remove the PoshC2 Project directory of: ${POSH_PROJECT_DIR}? y/N " -n 1 -r
echo ""
if [[ "$REPLY" =~ ^[Yy]$ ]]
then
    sudo rm -rf "$POSH_PROJECT_DIR"
fi

