#!/bin/bash

if [[ -z "${POSHC2_DIR}" ]]; then
     POSH_DIR="/opt/PoshC2_Python"
else
     POSH_DIR=${POSHC2_DIR}
fi

if [[ "$EDITOR" != "" ]]; then
    $EDITOR "$POSH_DIR/Config.py"
elif [[ "$*" == *"--nano"* ]]; then
    nano "$POSH_DIR/Config.py"
else
    vim "$POSH_DIR/Config.py"
fi
