#!/bin/bash

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    popd > /dev/null
    exit
}
    
if [[ -z "${POSHC2_DIR}" ]]; then
    POSH_DIR="/opt/PoshC2_Python"
else
    POSH_DIR=${POSHC2_DIR} 
fi

pushd $POSH_DIR  >/dev/null

if [ "$?" -eq "0" ]; then

    python2 -m pipenv run python2 -u C2Server.py | tee -a /var/log/poshc2_server.log
    popd > /dev/null

fi 

