#!/bin/bash

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    popd > /dev/null
    exit
}
    
if [[ -z "${POSHC2_DIR}" ]]; then
    POSH_DIR="/opt/PoshC2_Python"
else
    POSH_DIR=${POSHC2_DIR} 
fi

pushd $POSH_DIR  >/dev/null

if [ "$?" -eq "0" ]; then

    systemctl enable poshc2.service >/dev/null
    systemctl restart poshc2.service >/dev/null
	while [[ $x -le 10 ]]; do
	  if [ -f "/var/log/poshc2_server.log" ]; then
		  break;
	  fi
    sleep 1s
    x=$(( $x + 1 ))
  done
    /usr/bin/posh-log
    popd > /dev/null

fi 

