#!/bin/bash

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    popd > /dev/null
    exit
}
    
if [[ -z "${POSHC2_DIR}" ]]; then
    POSH_DIR="/opt/PoshC2"
else
    POSH_DIR=${POSHC2_DIR} 
fi

pushd $POSH_DIR  >/dev/null

if [ "$?" -eq "0" ]; then

    echo ""
    echo -e """\033[92m
       __________            .__.     _________  ________
       \_______  \____  _____|  |__   \_   ___ \ \_____  \\
        |     ___/  _ \/  ___/  |  \  /    \  \/  /  ____/
        |    |  (  <_> )___ \|   Y  \ \     \____/       \\
        |____|   \____/____  >___|  /  \______  /\_______ \\
                           \/     \/          \/         \/
        ================= www.PoshC2.co.uk ================"""
    echo ""
    echo "[+] Updating PoshC2"
    echo ""

    echo ""
    echo "[+] Saving changes to Config.py"
    echo ""
    git diff Config.py >> /tmp/PoshC2_Config_Diff.git

    echo ""
    echo "[+] Updating Posh Installation to latest master"
    git fetch
    git reset --hard origin/master

    echo ""
    echo "[+] Running Install script"
    ./Install.sh

    echo ""
    echo "[+] Re-applying Config file changes"
    git apply /tmp/PoshC2_Config_Diff.git

    if [ "$?" -eq "0" ]; then
        rm /tmp/PoshC2_Config_Diff.git
    else
        echo "[-] Re-applying Config file changes failed, please merge manually from /tmp/PoshC2_Config_Diff.git"
    fi

    echo ""
    echo "[+] Update complete"
    echo ""

    popd > /dev/null

fi 
